try {
  hello();
} catch (error) {
  console.log(error);
}

try {
  anotherFunction();
} catch (error) {
  console.log("There was an error");
}
